# There is only OBJECT, there is no such thing as NUMBER

In [17]:
from IPython.core.interactiveshell import InteractiveShell; InteractiveShell.ast_node_interactivity = "all"
a=1
a
type(a)
b=1.0
b
type(b)

c=1
c
d=1.0
d

id(a)
id(c)

id(b)
id(d)
a is c
a is b
a == b
a == d
# a, b, c are references to existing objects

1

int

1.0

float

1

1.0

140717258975024

140717258975024

1915743762544

1915709057776

True

False

True

True

1915743763088

1915743762608

# OPERATOR is implemented as METHOD

In [2]:
# dir(a)
# help(a.__add__)
a.__add__(a)
a.__add__(b)
b.__add__(a)
a + b

2

NotImplemented

2.0

2.0

# STRING

In [3]:
str(a)
str(b)
'HELLO KITTY'
'HELLO KITTY'.lower()
'A\n\tB'
r'''A
    B'''
r'\LaTeX\n'

f'I eat {a+b} meals a day.'
f'I eat {a+int(b):d} meals a day.'

'1'

'1.0'

'HELLO KITTY'

'hello kitty'

'A\n\tB'

'A\n    B'

'\\LaTeX\\n'

'I eat 2.0 meals a day.'

'I eat 2 meals a day.'

# ITERABLE

In [5]:
LIST = [0, 1, 2]
TUPLE = 0, 1, 2 # tuple(LIST)
DICT = {0:'A', 1:'B', 2:'C'} # DICT = dict([(0,'A'), (1,'B'), (2,'C')])
LIST
TUPLE
DICT

# UNPACK
x, y, _ = TUPLE
x
y

print('-'*40)
for el in LIST: print(el)
for el in TUPLE: print(el)
for key, val in DICT.items(): print(key, val)

print('-'*40)
for index, el in enumerate(LIST): print(index, el)
for index, el in enumerate(TUPLE): print(index, el)
for index, (key, val) in enumerate(DICT.items()): print(index, key, val)

[0, 1, 2]

(0, 1, 2)

{0: 'A', 1: 'B', 2: 'C'}

0

1

----------------------------------------
0
1
2
0
1
2
0 A
1 B
2 C
----------------------------------------
0 0
1 1
2 2
0 0
1 1
2 2
0 0 A
1 1 B
2 2 C


In [6]:
# MODIFY or NEW
LIST.append(999)
LIST + LIST

TUPLE + TUPLE

DICT[999] = 'ZZZ'
DICT.update(DICT)
DICT

[0, 1, 2, 999, 0, 1, 2, 999]

(0, 1, 2, 0, 1, 2)

{0: 'A', 1: 'B', 2: 'C', 999: 'ZZZ'}

In [7]:
# LIST.max()
# help(max)
max(LIST)

# COMPREHENSION
LIST[-1]
LIST[:-2]
LIST[-2:]
LIST[::2]
LIST[::-1]

999

999

[0, 1]

[2, 999]

[0, 2]

[999, 2, 1, 0]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# CLASS

In [18]:
class EE275:
    title = 'electric motors and motion control'
    def __init__(self, year, teacher):
        EE275.y = year
        EE275.t = teacher
#         self.y = year
#         self.t = teacher
ee2023 = EE275(2023, 'Chen')
ee2024 = EE275(2024, 'Xu')
ee2023.y
ee2024.y
ee2023.title

2024

2024

'electric motors and motion control'

# NUMPY

In [10]:
from pylab import np
np.arange(10, 100, 10)
np.arange(0, 1, .1)


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])